eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #this service as a client do not register ownself
    fetch-registry: false   #do not fetch registry
server:
  port: 8761